import {
  WHITE_COLOR,
  COAL_COLOR,
  GREY_COLOR,
  LIGHT_GREY_COLOR,
  DARK_GREY_COLOR,
  SECONDARY_GREY,
  LIGHTER_GREY_COLOR,
  GREEN_COLOR,
  LIGHT_RED_COLOR,
  BLUE_COLOR,
  LIGHT_BLUE_COLOR,
} from './colors';
import { commonTheme, toast } from './common';

export const theme: Record<string, any> = {
    ...commonTheme,
    name: 'default',
    faviconName: 'smartspace',
    logoImage: 'smartspace',
    bgColor: WHITE_COLOR,
    bgItemColor: LIGHT_GREY_COLOR,
    bgConfirmColor: GREEN_COLOR,
    bgActionColor: COAL_COLOR,
    borderColor: COAL_COLOR,
    borderFocusColor: LIGHT_RED_COLOR,
    contentHeaderBgColor: DARK_GREY_COLOR,
    contentHeaderSecondaryBgColor: LIGHTER_GREY_COLOR,
    textColorMain: LIGHT_RED_COLOR,
    textColorRegular: COAL_COLOR,
    textColorRevert: WHITE_COLOR,
    textColorNotes: SECONDARY_GREY,
    iconColorMain: GREY_COLOR,
    highlightColor: LIGHT_RED_COLOR,
    bgBackground: '#5aafe2',
    linkColor: LIGHT_BLUE_COLOR,
    statusButtonBg: GREEN_COLOR,
    routeButtonBg: LIGHT_RED_COLOR,
    uploadButtonBg: LIGHT_RED_COLOR,
    sliderColor: LIGHT_RED_COLOR,
    sortButtonColor: BLUE_COLOR,
    toast,
  };